def get_html_template(content):
    return f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>News Agent Digest</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
        <style>
            body {{ font-family: 'Inter', sans-serif; background-color: #0f172a; color: #f8fafc; }}
            .glass {{ background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.1); }}
            .gradient-text {{ background: linear-gradient(135deg, #38bdf8, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
        </style>
    </head>
    <body class="min-h-screen p-8">
        <div class="max-w-4xl mx-auto">
            <header class="mb-12 text-center">
                <h1 class="text-5xl font-bold gradient-text mb-4">News Agent Digest</h1>
                <p class="text-slate-400">Your AI-curated market and technology briefing</p>
            </header>
            
            <main class="glass rounded-3xl p-8 shadow-2xl border border-slate-700/50">
                <div class="prose prose-invert max-w-none">
                    {content}
                </div>
            </main>
            
            <footer class="mt-12 text-center text-slate-500 text-sm">
                Generated by NewsAgent AI • Powered by CrewAI & Ollama
            </footer>
        </div>
    </body>
    </html>
    """
